### ISSUE TITLE
nextDay function assumes all months have 30 days.

### ISSUE THREAD

**Issue by vdalv** [kammitama5/Distracting_KATAS#2]
This line: `elif (day == 30):` in the nextDay function (adddays.py file) assumes that all of the months have 30 days. I could add another function to fix this, but it looks like you're interested in coding stuff yourself.

You could also account for leap years, if you're interested in doing so.

**Comment by kammitama5** [comment]
yep...this is for a Udacity course. It's the first part, before we account for regular months. But thanks..I'll merge :) Essentially, the rest of the coursework does account for both leap years and for regular days, but I didn't post this code (I don't want to post all of the code for the course on my GH). If you're interested...here is a repl.it with the code -> https://repl.it/KEQr
